version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: cd ios
      - run: pod install
      - run: fastlane scan
      
workflows:
    build-and-test:
      jobs:
        - build-and-test