version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "10.3"
    steps:
      - checkout
      - run: cd ios && fastlane scan
workflows:
    build-and-test:
      jobs:
        - build-and-test