version: 2.1

steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install --verbose

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
      
workflows:
    build-and-test:
      jobs:
        - build-and-test