version: 2.1
orbs:
  node: circleci/node@1.1.6
  
jobs:
  build-and-test:
    macos:
      xcode: "11.3"
    steps:
      - checkout
      - run: cd ios && bundle exec fastlane scan
workflows:
    build-and-test:
      jobs:
        - build-and-test